### ISSUE TITLE
Flutter Flavors

### ISSUE THREAD

**Issue by amanxnanda** [commclassroom/mobileapp#1]
Introduce flutter flavors, it can help developing applications in different environments i.e. Dev, Test, or Prod. 
It can also ensure the safekeeping of the DB / backend from corrupting or deleting.

**Comment by Sahil-kachhap** [comment]
> Introduce flutter flavors, it can help developing applications in different environments i.e. Dev, Test, or Prod.
> It can also ensure the safekeeping of the DB / backend from corrupting or deleting.

It's good thing to implement flavors but I had a doubt whether we can't make use of seperate git branches for each environment and application features. (By default our main branch would act as our production environment).

**Comment by amanxnanda** [comment]
Branching is great. But developers may have to swap out dev and prod API keys, google services, etc. If you are planning to use any of the Firebase Services i.e. Analytics, Crashlytics, Firestore, FCM, etc then am not sure how safe it is to keep the PROD google-services.json file in a public repo (yes, we can keep that in GitHub secrets). Even then you'll have to give Devs/Community a dev google services version so they can test out things themselves.

**Comment by Sahil-kachhap** [comment]
> Branching is great. But developers may have to swap out dev and prod API keys, google services, etc. If you are planning to use any of the Firebase Services i.e. Analytics, Crashlytics, Firestore, FCM, etc then am not sure how safe it is to keep the PROD google-services.json file in a public repo (yes, we can keep that in GitHub secrets). Even then you'll have to give Devs/Community a dev google services version so they can test out things themselves.

Ok yes , that would be good. I didn't thought about this thing. 👍

**Comment by thisisamank** [comment]
Thank you for your suggestions, Right now our focus is to build the initial MVP and later on more things will be added.

**Comment by thisisamank** [comment]
I'm closing this issue for now.
